#!/bin/bash
awk '
/async refreshConversationMemory\(/ {
    print "  // [AGENTIC REFACTOR] Nâng cấp Trí nhớ khách hàng (Phase 2)"
    print "  async refreshConversationMemory("
    print "    conversationId: string,"
    print "    @MedusaContext() sharedContext: Context = {}"
    print "  ) {"
    print "    const conversation = await this.retrieveAgentConversation(conversationId, {}, sharedContext);"
    print "    // Lấy TẤT CẢ tin nhắn chưa tóm tắt (không giới hạn take: 6 nữa)"
    print "    const [messages, messageCount] = await this.listAndCountAgentMessages("
    print "      { conversation_id: conversation.id },"
    print "      { order: { occurred_at: \"DESC\" }, take: 100 },"
    print "      sharedContext"
    print "    );"
    print "    const latestMessage = messages[0];"
    print "    if (!latestMessage) return { memory: null, updated: false };"
    print "    "
    print "    const existing = ("
    print "      await this.listAgentConversationMemories("
    print "        { conversation_id: conversation.id },"
    print "        { take: 1 },"
    print "        sharedContext"
    print "      )"
    print "    )[0];"
    print "    if (existing?.last_message_id === latestMessage.id) {"
    print "      return { memory: existing, updated: false };"
    print "    }"
    print "    "
    print "    const orderedMessages = messages.slice().reverse();"
    print "    const previousMessageIndex = existing"
    print "      ? orderedMessages.findIndex(m => m.id === existing.last_message_id)"
    print "      : -1;"
    print "    "
    print "    const unsummarizedMessages = orderedMessages"
    print "      .slice(previousMessageIndex >= 0 ? previousMessageIndex + 1 : 0)"
    print "      .map(m => ({"
    print "        content: m.body, // Không slice(0,800) nữa, lấy toàn bộ"
    print "        role: m.direction === \"INBOUND\" ? \"user\" : \"assistant\""
    print "      }));"
    print "      "
    print "    if (unsummarizedMessages.length === 0) return { memory: existing, updated: false };"
    print "    "
    print "    const credentials = await this.getActiveAiProviderCredentials(\"generation\", conversation.tenant_id);"
    print "    if (!credentials.length) return { memory: existing, updated: false };"
    print "    "
    print "    const { MemoryEngine } = await import(\"./memory-engine\");"
    print "    const engine = new MemoryEngine(credentials[0].api_key, credentials[0].model);"
    print "    "
    print "    const previousMemoryObj = existing ? {"
    print "      summary: existing.summary,"
    print "      customer_facts: typeof existing.customer_facts === \"string\" ? JSON.parse(existing.customer_facts) : existing.customer_facts,"
    print "      open_questions: typeof existing.open_questions === \"string\" ? JSON.parse(existing.open_questions) : existing.open_questions,"
    print "      resolved_topics: typeof existing.resolved_topics === \"string\" ? JSON.parse(existing.resolved_topics) : existing.resolved_topics"
    print "    } : null;"
    print "    "
    print "    const memoryUpdate = await engine.summarizeConversation(previousMemoryObj, unsummarizedMessages);"
    print "    "
    print "    // Lưu Memory mới"
    print "    const data = {"
    print "      summary: memoryUpdate.summary,"
    print "      customer_facts: JSON.stringify(memoryUpdate.customer_facts),"
    print "      open_questions: JSON.stringify(memoryUpdate.open_questions),"
    print "      resolved_topics: JSON.stringify(memoryUpdate.resolved_topics),"
    print "      last_message_id: latestMessage.id,"
    print "      source_message_count: messageCount,"
    print "      summarized_at: new Date()"
    print "    };"
    print "    "
    print "    const memory = existing"
    print "      ? await this.updateAgentConversationMemories({ ...data, id: existing.id }, sharedContext)"
    print "      : await this.createAgentConversationMemories({ ...data, conversation_id: conversation.id }, sharedContext);"
    print "    "
    print "    // Lưu Preference (thông số chiều cao, cân nặng, VIP) vào DB"
    print "    if (memoryUpdate.extracted_preferences && memoryUpdate.extracted_preferences.length > 0) {"
    print "      const metadata = (conversation.metadata ?? {}) as Record<string, unknown>;"
    print "      const customerId = metadata.customer_id as string;"
    print "      if (customerId) {"
    print "        for (const pref of memoryUpdate.extracted_preferences) {"
    print "          await this.createAgentCustomerPreferences({"
    print "            tenant_id: conversation.tenant_id,"
    print "            customer_id: customerId,"
    print "            preference_type: pref.preference_type,"
    print "            value: pref.value,"
    print "            status: \"CUSTOMER_STATED\","
    print "            source_conversation_id: conversation.id,"
    print "            source_message_id: latestMessage.id"
    print "          }, sharedContext);"
    print "        }"
    print "      }"
    print "    }"
    print "    "
    print "    return { memory, updated: true };"
    print "  }"
    
    skip = 1
    next
}
skip && /async processCustomerMessageAgentic/ {
    skip = 0
}
!skip {
    print
}
' src/modules/agent-operations/service.ts > tmp_mem.ts && mv tmp_mem.ts src/modules/agent-operations/service.ts
