export const AGENT_RBAC_POLICY_DEFINITIONS = [
  { name: "AgentEventCreate", resource: "agent_event", operation: "create" },
  { name: "AgentIncidentRead", resource: "agent_incident", operation: "read" },
  { name: "AgentApprovalRead", resource: "agent_approval", operation: "read" },
  { name: "AgentApprovalApprove", resource: "agent_approval", operation: "approve" },
  { name: "AgentActionRead", resource: "agent_action", operation: "read" },
  { name: "AgentActionCreate", resource: "agent_action", operation: "create" },
  { name: "AgentActionExecute", resource: "agent_action", operation: "execute" },
  { name: "AgentToolRead", resource: "agent_tool", operation: "read" },
  { name: "AgentConversationRead", resource: "agent_conversation", operation: "read" },
  { name: "AgentMessageCreate", resource: "agent_message", operation: "create" },
  { name: "AgentSupportSimulatorCreate", resource: "agent_support_simulator", operation: "create" },
  { name: "AgentTaskRead", resource: "agent_task", operation: "read" },
  { name: "AgentTaskCreate", resource: "agent_task", operation: "create" },
  { name: "AgentTaskUpdate", resource: "agent_task", operation: "update" },
  { name: "AgentKnowledgeRead", resource: "agent_knowledge", operation: "read" },
  { name: "AgentKnowledgeCreate", resource: "agent_knowledge", operation: "create" },
  { name: "AgentKnowledgeApprove", resource: "agent_knowledge", operation: "approve" },
  { name: "AgentKnowledgeDelete", resource: "agent_knowledge", operation: "delete" },
  { name: "AgentAiProviderRead", resource: "agent_ai_provider", operation: "read" },
  { name: "AgentAiProviderConfigure", resource: "agent_ai_provider", operation: "configure" },
  { name: "AgentAiProviderDelete", resource: "agent_ai_provider", operation: "delete" },
  { name: "AgentEvaluationRead", resource: "agent_evaluation", operation: "read" },
  { name: "AgentEvaluationExecute", resource: "agent_evaluation", operation: "execute" },
  { name: "AgentCatalogRead", resource: "agent_catalog", operation: "read" },
  { name: "AgentPlatformRead", resource: "agent_platform", operation: "read" },
  { name: "AgentPlatformConfigure", resource: "agent_platform", operation: "configure" },
] as const

export const CUSTOMER_SUPPORT_STAFF_ROLE_NAME = "customer_support_staff"

export const CUSTOMER_SUPPORT_STAFF_POLICY_KEYS = [
  "agent_action:create",
  "agent_action:execute",
  "agent_conversation:read",
  "agent_message:create",
  "agent_support_simulator:create",
  "agent_task:read",
  "agent_task:update",
  "customer:read",
  "order:read",
] as const
